package com.android.gudana.MoD;

public class LiveTrackingObjet {

    public  String CONTACTS_TABLE_MATRITCULE_LIVE = "MATRICULE";
    public  String CONTACTS_COLUMN_START_TIME = "STARTED_AT";
    public  String CONTACTS_COLUMN_SHARING_TYPE = "SHARING_TYPE";
    public  String CONTACTS_COLUMN_MESSAGE = "MESSAGE";
    public  String CONTACTS_COLUMN_ID_USER = "ID_USER";
    public  String CONTACTS_COLUMN_ACTIV= "STATUS";

    public LiveTrackingObjet(String CONTACTS_TABLE_MATRITCULE_LIVE,
                             String CONTACTS_COLUMN_START_TIME,
                             String CONTACTS_COLUMN_SHARING_TYPE,
                             String CONTACTS_COLUMN_MESSAGE,
                             String CONTACTS_COLUMN_ID_USER,
                             String CONTACTS_COLUMN_ACTIV) {

        this.CONTACTS_TABLE_MATRITCULE_LIVE = CONTACTS_TABLE_MATRITCULE_LIVE;
        this.CONTACTS_COLUMN_START_TIME = CONTACTS_COLUMN_START_TIME;
        this.CONTACTS_COLUMN_SHARING_TYPE = CONTACTS_COLUMN_SHARING_TYPE;
        this.CONTACTS_COLUMN_MESSAGE = CONTACTS_COLUMN_MESSAGE;
        this.CONTACTS_COLUMN_ID_USER = CONTACTS_COLUMN_ID_USER;
        this.CONTACTS_COLUMN_ACTIV = CONTACTS_COLUMN_ACTIV;
    }

    public String getCONTACTS_TABLE_MATRITCULE_LIVE() {
        return CONTACTS_TABLE_MATRITCULE_LIVE;
    }

    public void setCONTACTS_TABLE_MATRITCULE_LIVE(String CONTACTS_TABLE_MATRITCULE_LIVE) {
        this.CONTACTS_TABLE_MATRITCULE_LIVE = CONTACTS_TABLE_MATRITCULE_LIVE;
    }


    public String getCONTACTS_COLUMN_START_TIME() {
        return CONTACTS_COLUMN_START_TIME;
    }

    public void setCONTACTS_COLUMN_START_TIME(String CONTACTS_COLUMN_START_TIME) {
        this.CONTACTS_COLUMN_START_TIME = CONTACTS_COLUMN_START_TIME;
    }

    public String getCONTACTS_COLUMN_SHARING_TYPE() {
        return CONTACTS_COLUMN_SHARING_TYPE;
    }

    public void setCONTACTS_COLUMN_SHARING_TYPE(String CONTACTS_COLUMN_SHARING_TYPE) {
        this.CONTACTS_COLUMN_SHARING_TYPE = CONTACTS_COLUMN_SHARING_TYPE;
    }

    public String getCONTACTS_COLUMN_MESSAGE() {
        return CONTACTS_COLUMN_MESSAGE;
    }

    public void setCONTACTS_COLUMN_MESSAGE(String CONTACTS_COLUMN_MESSAGE) {
        this.CONTACTS_COLUMN_MESSAGE = CONTACTS_COLUMN_MESSAGE;
    }

    public String getCONTACTS_COLUMN_ID_USER() {
        return CONTACTS_COLUMN_ID_USER;
    }

    public void setCONTACTS_COLUMN_ID_USER(String CONTACTS_COLUMN_ID_USER) {
        this.CONTACTS_COLUMN_ID_USER = CONTACTS_COLUMN_ID_USER;
    }

    public String getCONTACTS_COLUMN_ACTIV() {
        return CONTACTS_COLUMN_ACTIV;
    }

    public void setCONTACTS_COLUMN_ACTIV(String CONTACTS_COLUMN_ACTIV) {
        this.CONTACTS_COLUMN_ACTIV = CONTACTS_COLUMN_ACTIV;
    }
}
